-- +goose Up
ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN subscribed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN summarize BOOLEAN NOT NULL DEFAULT FALSE;



-- +goose Down
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users DROP COLUMN subscribed;
ALTER TABLE users DROP COLUMN summarize;
